apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: otel
  labels:
    app: opentelemetry
    component: jaeger-all-in-one
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: jaeger-all-in-one
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: jaeger-all-in-one
    spec:
      containers:
      - name: jaeger-all-in-one
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686 # ui
        - containerPort: 14268 # jaeger thift
        - containerPort: 14250 # jaeger model.proto
