apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
  namespace: otel
  labels:
    app: opentelemetry
    component: jaeger-all-in-one
spec:
  selector:
    component: jaeger-all-in-one
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: thrift
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: proto
      protocol: TCP
      port: 14250
      targetPort: 14250
