apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector-dev:latest
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 1888 # Default endpoint for pprof
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 13133 # Default endpoint for health_check
        - containerPort: 8888  # Default endpoint for otel-collector metrics.
        - containerPort: 55678 # default port for OpenCensus receiver
        - containerPort: 8889 # default port for prometheus exporter
        # - containerPort: 55680 # Default endpoint for OpenTelemetry receiver.
        # - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
        # - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        # - containerPort: 9411 # Default endpoint for Zipkin receiver.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
