---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    component: otel-collector
  ports:
    - name: pprof
      protocol: TCP
      port: 1888
      targetPort: 1888
    - name: zpages
      protocol: TCP
      port: 55679
      targetPort: 55679
    - name: health-check
      protocol: TCP
      port: 13133
      targetPort: 13133
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: opencensus-receiver
      protocol: TCP
      port: 55678
      targetPort: 55678
    - name: prom-exporter
      protocol: TCP
      port: 8889
      targetPort: 8889
