apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: otel
  labels:
    app: opentelemetry
    component: prometheus
data:
  prometheus: |
    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
          - targets: ['otel-collector.otel.svc.cluster.local:8889']
          - targets: ['otel-collector.otel.svc.cluster.local:8888']
