apiVersion: v1
kind: Service
metadata:
  name: zipkin-all-in-one
  namespace: otel
  labels:
    app: opentelemetry
    component: zipkin-all-in-one
spec:
  selector:
    component: zipkin-all-in-one
  ports:
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
