apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent
  namespace: otel
  labels:
    app: opentelemetry
    component: otel-agent
data:
  otel-agent-config: |
    receivers:
      opencensus:
      zipkin:
        endpoint: :9411
      jaeger:
        protocols:
          thrift_http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'load_generator_app'
              scrape_interval: 3s
              static_configs:
                - targets: ['load-generator.otel.svc.cluster.local:9001']
    exporters:
      opencensus:
        endpoint: "otel-collector.otel.svc.cluster.local:55678"
        insecure: true
      logging:
        loglevel: debug
    processors:
      batch:
      queued_retry:

    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [opencensus, jaeger, zipkin]
          exporters: [opencensus, logging]
          processors: [batch, queued_retry]
        metrics:
          receivers: [opencensus, prometheus]
          exporters: [logging,opencensus]
